server:
  port: 7002
  
spring:
  datasource:
    url: '@URL@'
    username: '@dataSource.project.user@'
    password: '@dataSource.project.password@'
    driver-class-name: '@dataSource.project.driverClass@'
    
  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        ddl-auto: create-drop          
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true

